apiVersion: v1
data:
  config.json: |
    {
      "local": {
        "username": "{{ .Values.database.username }}",
        "password": "{{ .Values.database.password }}",
        "database": "{{ .Values.database.database }}",
        "host": "{{ .Values.database.host }}",
        "dialect": "{{ .Values.database.dialect }}"
      }
    }
kind: ConfigMap
metadata:
  name: account-management-config
